### ISSUE TITLE
terraform registry publication

### ISSUE THREAD

**Issue by poblin-orange** [rundeck/terraform-provider-rundeck#59]
### Terraform Version

terraform 0.13

### Expected Behavior
I expect to find this nice plugin in terraform registry 
https://registry.terraform.io/

**Comment by codayblue** [comment]
I was worried this provider was removed when I could not find it on the registry. Is there anything I can do to help get this up into the registry?

**Comment by qualman** [comment]
Hi all, thanks for sending this in. I've published our [provider](https://registry.terraform.io/providers/rundeck/rundeck/latest) to Teraform Registry once again. It's a version behind (working on that presently) but otherwise available. Let me know if you have any questions or issues!

Thanks,
Jason
Software Engineer | Rundeck

**Comment by qualman** [comment]
And the latest version is up!

Thanks,
Jason
